CREATE TABLE "log" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "level" varchar,
  "source" varchar UNIQUE,
  "user_id" integer,
  "event_code" text,
  "message" varchar,
  "details" jsonb,
  "ip" varchar,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar UNIQUE,
  "email" varchar UNIQUE,
  "name" varchar,
  "resume" text,
  "picture" varchar,
  "updated_at" timestamp DEFAULT (now()),
  "created_at" timestamp DEFAULT (now()),
  "role_id" integer DEFAULT 1
);

CREATE TABLE "enrollments" (
  "user_id" integer,
  "course_id" integer,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "roles" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "role" varchar UNIQUE
);

CREATE TABLE "courses" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar,
  "descrition" text,
  "featured_image" varchar,
  "permisson_id" integer,
  "user_id" integer,
  "updated_at" timestamp DEFAULT (now()),
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "categoryTypes" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "descrition" text
);

CREATE TABLE "categorys" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "descrition" text,
  "categoryType_id" integer
);

CREATE TABLE "categorys_subCategorys" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "category_id" integer,
  "subCategory_id" integer
);

CREATE TABLE "category_subCategory_course" (
  "id" integer PRIMARY KEY,
  "category_subCategory_id" integer,
  "course_id" integer
);

CREATE TABLE "modules" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar,
  "course_id" integer,
  "descrition" text,
  "updated_at" timestamp DEFAULT (now()),
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "follows_user" (
  "following_user_id" integer,
  "followed_user_id" integer,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "permissons" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar UNIQUE
);

CREATE TABLE "lessons" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order" integer,
  "title" varchar,
  "lesson" jsonb,
  "updated_at" timestamp DEFAULT (now()),
  "created_at" timestamp DEFAULT (now()),
  "module_id" integer
);

CREATE TABLE "lessonCompletions" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "lesson_id" integer,
  "user_id" integer,
  "created_at" timestamp DEFAULT (now())
);

ALTER TABLE "users" ADD FOREIGN KEY ("role_id") REFERENCES "roles" ("id");

ALTER TABLE "enrollments" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "enrollments" ADD FOREIGN KEY ("course_id") REFERENCES "courses" ("id");

ALTER TABLE "courses" ADD FOREIGN KEY ("permisson_id") REFERENCES "permissons" ("id");

ALTER TABLE "courses" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "categorys" ADD FOREIGN KEY ("categoryType_id") REFERENCES "categoryTypes" ("id");

ALTER TABLE "categorys_subCategorys" ADD FOREIGN KEY ("category_id") REFERENCES "categorys" ("id");

ALTER TABLE "categorys_subCategorys" ADD FOREIGN KEY ("subCategory_id") REFERENCES "categorys" ("id");

ALTER TABLE "category_subCategory_course" ADD FOREIGN KEY ("category_subCategory_id") REFERENCES "categorys_subCategorys" ("id");

ALTER TABLE "category_subCategory_course" ADD FOREIGN KEY ("course_id") REFERENCES "courses" ("id");

ALTER TABLE "modules" ADD FOREIGN KEY ("course_id") REFERENCES "courses" ("id");

ALTER TABLE "follows_user" ADD FOREIGN KEY ("following_user_id") REFERENCES "users" ("id");

ALTER TABLE "follows_user" ADD FOREIGN KEY ("followed_user_id") REFERENCES "users" ("id");

ALTER TABLE "lessons" ADD FOREIGN KEY ("module_id") REFERENCES "modules" ("id");

ALTER TABLE "lessonCompletions" ADD FOREIGN KEY ("lesson_id") REFERENCES "lessons" ("id");

ALTER TABLE "lessonCompletions" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");
