package domain

import "time"

// gorm.user definition
type Courses struct {
	ID            int64 `gorm:"primaryKey";`
	Title         string
	Descrition    string
	FeaturedImage string
	PermissonID   int       `gorm:"column:permisson_id"`
	UserID        int       `gorm:"column:user_id"`
	Updated_at    time.Time `gorm:"default:now()"`
	Created_at    time.Time `gorm:"default:now()"`
	Modules       []Module  `gorm:"foreignKey:CourseID"`
}

/*
CREATE TABLE "courses" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar,
  "descrition" text,
  "featured_image" varchar,
  "permisson_id" integer,
  "user_id" integer,
  "updated_at" timestamp DEFAULT (now()),
  "created_at" timestamp DEFAULT (now())
);
*/
