package domain

import "encoding/json"

// gorm.Modules definition
type Lesson struct {
	ID       int64 `gorm:"primaryKey";`
	Order    int16
	Title    string
	Lesson   json.RawMessage
	ModuleID int64
	Module   Module `gorm:"foreignKey:ModuleID"`
}

/*
CREATE TABLE "lessons" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order" integer,
  "title" varchar,
  "lesson" jsonb,
  "updated_at" timestamp DEFAULT (now()),
  "created_at" timestamp DEFAULT (now()),
  "module_id" integer
);
*/
