package domain

// gorm.Modules definition
type Module struct {
	ID         int64 `gorm:"primaryKey";`
	Title      string
	Descrition string
	CourseID   int64    `gorm:"column:course_id"` // Garantir que corresponda ao tipo do ID em Courses
	Course     Courses  `gorm:"foreignKey:CourseID"`
	Lessons    []Lesson `gorm:"foreignKey:ModuleID"`
}

/*
CREATE TABLE "modules" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar,
  "course_id" integer,
  "descrition" text,
  "updated_at" timestamp DEFAULT (now()),
  "created_at" timestamp DEFAULT (now())
);
*/
