package domain

import "time"

// gorm.user definition
type Users struct {
	ID         int64  `gorm:"primaryKey";`
	Username   string `gorm:"type:varchar(255);unique;not null"`
	Email      string `gorm:"type:varchar(255);unique;not null"`
	Name       string `gorm:"type:varchar(255);not null"`
	Resume     string
	Picture    string `gorm:"type:varchar(255);not null"`
	RoleID     int    `gorm:"column:role_id"`
	Updated_at time.Time
	Created_at time.Time
}

/*
CREATE TABLE "users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar UNIQUE,
  "email" varchar UNIQUE,
  "name" varchar,
  "resume" text,
  "picture" varchar,
  "updated_at" timestamp DEFAULT (now()),
  "created_at" timestamp DEFAULT (now()),
  "role_id" integer DEFAULT 1
);
*/
